/* The full concept list from the DSA + AI Engineer Mastery Roadmap handbook,
   grouped by its Part. test_roadmap.js asserts the dictionary defines every
   one of these, so a reader who meets a term in that handbook can always look
   it up here.

   Four entries are deliberately listed under the handbook's wording while the
   dictionary holds them under a clearer title; ALIAS in test_roadmap.js maps
   those. Add to this list when the handbook is revised. */

const PDF = {
  "I DSA — structures": ["Array", "Hash Table", "Linked List", "Stack", "Queue", "Deque", "Heap",
    "Binary Search Tree", "Trie", "Graph", "Union-Find", "Segment Tree", "Fenwick Tree",
    "AVL Tree", "Red-Black Tree", "B-Tree", "Morris Traversal", "LRU Cache", "LFU Cache"],
  "I DSA — the 20 patterns": ["Two Pointers", "Sliding Window", "Fast and Slow Pointers",
    "Prefix Sum", "Difference Array", "Merge Intervals", "Sweep Line", "Cyclic Sort",
    "Monotonic Stack", "Top-K", "Two Heaps", "Binary Search", "Binary Search on the Answer",
    "Breadth-First Search", "Depth-First Search", "Backtracking", "Topological Sort",
    "Dynamic Programming", "Greedy Algorithm", "Bit Manipulation", "Matrix"],
  "I DSA — underrated": ["Multi-Source BFS", "0-1 BFS", "Quickselect", "Reservoir Sampling",
    "KMP", "Z-Algorithm", "Rabin-Karp", "Rolling Hash", "Manacher's Algorithm", "Bitmask DP",
    "Digit DP", "Hash Flooding", "Amortised Analysis", "Inverse Ackermann"],
  "I DSA — graphs": ["Dijkstra's Algorithm", "Bellman-Ford", "Floyd-Warshall", "Kruskal's Algorithm",
    "Prim's Algorithm", "Minimum Spanning Tree", "Tarjan's Algorithm", "Kosaraju's Algorithm",
    "Strongly Connected Component", "Binary Lifting", "Sqrt Decomposition", "Sparse Table"],
  "I DSA — DP patterns": ["Knapsack", "Longest Increasing Subsequence", "Longest Common Subsequence",
    "Edit Distance", "Interval DP", "Matrix Chain Multiplication", "Grid DP", "State Machine DP",
    "DP on Trees", "Memoisation", "Tabulation", "Optimal Substructure", "Overlapping Subproblems"],
  "I DSA — sorting": ["Quick Sort", "Merge Sort", "Heapsort", "Insertion Sort", "Counting Sort",
    "Radix Sort", "Timsort", "Sorting Stability"],
  "II SWE": ["Type Hints", "Pydantic", "Async/Await", "Pytest", "Poetry", "Tenacity",
    "Structured Logging", "cProfile", "Generator", "Global Interpreter Lock", "FastAPI",
    "Docker", "Kubernetes", "GitHub Actions", "Server-Sent Events", "WebSocket",
    "Window Function", "Common Table Expression", "pgvector", "Airflow", "dbt", "Spark"],
  "III Maths": ["Cosine Similarity", "Dot Product", "Softmax", "Cross-Entropy", "Perplexity",
    "Gradient Descent", "Confidence Interval", "A/B Testing", "Statistical Significance",
    "Eigenvector", "Principal Component Analysis"],
  "IV Classical ML": ["Bias-Variance Tradeoff", "Overfitting", "Underfitting", "Precision", "Recall",
    "F1 Score", "ROC-AUC", "PR-AUC", "Data Leakage", "SMOTE", "Class Imbalance", "Regularisation",
    "Lasso", "Ridge Regression", "Random Forest", "XGBoost", "Gradient Boosting", "K-Means Clustering",
    "DBSCAN", "t-SNE", "UMAP", "Cross-Validation", "Stratified Sampling"],
  "V Deep learning": ["Backpropagation", "ReLU", "GELU", "SiLU", "Sigmoid", "Adam Optimiser",
    "AdamW", "Stochastic Gradient Descent", "Momentum", "Batch Normalisation", "Layer Normalisation",
    "RMSNorm", "Dropout", "Gradient Clipping", "Vanishing Gradient", "Exploding Gradient",
    "Convolutional Neural Network", "Recurrent Neural Network", "LSTM", "GRU", "Learning Rate",
    "Learning Rate Warmup", "Early Stopping", "Residual Connection"],
  "VI Transformers": ["Tokenisation", "Byte-Pair Encoding", "WordPiece", "SentencePiece",
    "Self-Attention", "Multi-Head Attention", "Scaled Dot-Product Attention", "Causal Masking",
    "Positional Encoding", "RoPE", "ALiBi", "Encoder", "Decoder", "KV Cache",
    "Grouped-Query Attention", "Multi-Query Attention", "Multi-Head Latent Attention",
    "FlashAttention", "Mixture of Experts", "Sliding Window Attention", "Mamba",
    "Quantisation", "GPTQ", "AWQ", "GGUF", "Pruning", "Knowledge Distillation",
    "Greedy Decoding", "Beam Search", "Temperature", "Top-k Sampling", "Top-p Sampling",
    "Min-p Sampling", "Speculative Decoding", "Continuous Batching", "PagedAttention",
    "Prefix Caching", "Chunked Prefill", "Prefill", "Decode", "Time To First Token", "VRAM"],
  "VII Training": ["Pretraining", "Supervised Fine-Tuning", "RLHF", "DPO", "GRPO", "ORPO", "KTO",
    "LoRA", "QLoRA", "PEFT", "Reward Model", "KL Divergence", "Catastrophic Forgetting"],
  "VIII RAG": ["Retrieval-Augmented Generation", "Chunking", "Chunk Overlap", "Embedding",
    "Vector Database", "HNSW", "IVFFlat", "Approximate Nearest Neighbour", "BM25", "Hybrid Search",
    "Reciprocal Rank Fusion", "Reranking", "Cross-Encoder", "Bi-Encoder", "HyDE", "GraphRAG",
    "Agentic RAG", "RAPTOR", "Multi-Hop", "Query Rewriting", "Contextual Retrieval",
    "Metadata Filtering", "RAGAS", "Context Recall", "Context Precision", "Faithfulness",
    "Recall@k", "Mean Reciprocal Rank", "nDCG", "Semantic Gap"],
  "IX Agents": ["AI Agent", "ReAct", "Tool Use", "Function Calling", "Model Context Protocol",
    "LangGraph", "LangChain", "LlamaIndex", "DSPy", "Multi-Agent System", "Agent Memory",
    "Episodic Memory", "Reflection", "Planner-Executor", "Stop Condition"],
  "X Evals": ["Evaluation", "LLM-as-a-Judge", "Golden Dataset", "Error Analysis", "Position Bias",
    "Verbosity Bias", "Self-Preference Bias", "MMLU", "GSM8K", "HumanEval", "SWE-bench",
    "MT-Bench", "Benchmark Contamination", "Benchmark Saturation", "DeepEval", "Promptfoo",
    "Regression Testing", "Eval Gate"],
  "XI LLMOps": ["vLLM", "SGLang", "TensorRT-LLM", "Text Generation Inference", "Ollama",
    "llama.cpp", "Semantic Caching", "Model Routing", "Model Cascade", "Prompt Compression",
    "Observability", "Distributed Tracing", "Langfuse", "LangSmith", "MLflow",
    "Weights and Biases", "Model Registry", "Feature Store", "Data Drift", "Concept Drift",
    "Canary Deployment", "Shadow Deployment", "Data Parallelism", "Tensor Parallelism",
    "Pipeline Parallelism", "FSDP", "DeepSpeed ZeRO", "Mixed Precision", "p99 Latency"],
  "XII Safety": ["Prompt Injection", "Indirect Prompt Injection", "Jailbreak", "Guardrail",
    "OWASP LLM Top 10", "Excessive Agency", "System Prompt Leakage", "Denial of Wallet",
    "PII Redaction", "Data Poisoning", "EU AI Act", "Red Teaming", "Egress Filtering"],
  "XIII System design": ["Load Balancing", "Consistent Hashing", "Cache Invalidation",
    "Thundering Herd", "Sharding", "Replication", "Message Queue", "CAP Theorem",
    "Eventual Consistency", "Rate Limiting", "Token Bucket", "Leaky Bucket", "Idempotency",
    "Two-Tower Model", "Train-Serve Skew", "Candidate Generation", "Cold Start"],
  "XIV Interview": ["Technical Interview", "Behavioural Interview", "STAR Method",
    "System Design Interview", "Take-Home Assignment", "Online Assessment"]
};
module.exports=PDF;