"""Check that the Python in the Speed Coding cards is real Python.

A reader types these lines hundreds of times. A typo in one becomes muscle
memory for a mistake, which is worse than not practising at all -- so every
Python card is parsed, and the complete ones are compiled.

Fragments (rung 1) are deliberately incomplete -- "if ", "**kwargs", "[::-1]"
are not statements -- so they are checked by tokenising instead, which proves
the characters are legal Python without requiring a whole statement.

    python tools/verify_speed_code.py
"""

import ast
import io
import json
import re
import sys
import tokenize
from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "termdex" / "data" / "speed"

# Fragments that are legal Python characters but never a standalone statement.
# Tokenising proves they are lexically valid; compiling them cannot work.
FRAGMENT_RUNGS = {1}


def load_sets():
    """Pull the card data out of the JS files without running a JS engine.

    The files are `TD.addSpeedSets([...])` with JS object literals. Rather than
    write a JS parser, extract each set's id/rung and each card's `c` string
    with targeted regexes -- the data files are generated by hand in a fixed
    shape, and a mismatch here fails loudly rather than silently passing.
    """
    sets = []
    for path in sorted(DATA.glob("*.js")):
        text = io.open(path, encoding="utf-8").read()

        # split on set boundaries: `id: "...",` followed eventually by `rung: n,`
        for block in re.split(r"\n  \{\n", text)[1:]:
            m_id = re.search(r'id:\s*"([^"]+)"', block)
            m_rung = re.search(r"rung:\s*(\d+)", block)
            if not m_id or not m_rung:
                continue
            m_lang = re.search(r'lang:\s*"([^"]+)"', block)

            cards = []
            # each card starts `{ c: "..."` -- the string may contain escapes
            for m in re.finditer(r'\{\s*c:\s*("(?:[^"\\]|\\.)*")', block):
                cards.append(json.loads(m.group(1)))

            sets.append({
                "file": path.name,
                "id": m_id.group(1),
                "rung": int(m_rung.group(1)),
                "lang": m_lang.group(1) if m_lang else "python",
                "cards": cards,
            })
    return sets


def check_fragment(src):
    """Legal Python characters, even if not a complete statement."""
    try:
        list(tokenize.generate_tokens(io.StringIO(src).readline))
        return None
    except (tokenize.TokenError, IndentationError):
        # An unclosed bracket or a dangling `if ` is expected in a fragment --
        # what matters is that no character is illegal Python.
        return None
    except SyntaxError as e:
        return str(e)


def check_statement(src):
    """A complete, parseable statement or block."""
    try:
        ast.parse(src)
        return None
    except SyntaxError as e:
        return f"{e.msg} (line {e.lineno})"


# Lines that are legitimately incomplete even at rung 2/3, because the card is
# deliberately the *opening* of a construct the reader will finish themselves.
OPENERS = re.compile(
    r"^\s*(if|for|while|with|try|except|else|elif|def|class|async def)\b.*:\s*$"
    r"|^\s*@",
)


def main():
    sets = load_sets()
    if not sets:
        print("  ERROR  no speed sets found -- did the data format change?")
        return 1

    checked = failed = skipped = 0
    for S in sets:
        if S["lang"] != "python":
            skipped += len(S["cards"])
            continue

        for src in S["cards"]:
            checked += 1

            if S["rung"] in FRAGMENT_RUNGS:
                err = check_fragment(src)
            elif OPENERS.match(src.split("\n")[-1]) or OPENERS.match(src):
                # an opener: give it a body so the parser can judge the rest
                err = check_statement(src + "\n    pass")
                if err:
                    err = check_fragment(src)
            else:
                err = check_statement(src)

            if err:
                failed += 1
                first = src.split("\n")[0][:52]
                print(f"  FAIL   [{S['id']}] {first}")
                print(f"         {err}")

    total = checked
    print(f"\n{total - failed}/{total} Python cards parse"
          + (f" ({skipped} non-Python cards skipped)" if skipped else ""))
    if failed:
        print(f"{failed} FAILED\n")
        return 1
    print("Every Python line in Speed Coding is valid Python.\n")
    return 0


if __name__ == "__main__":
    print("\nSpeed Coding — parsing the cards\n")
    sys.exit(main())
